language: python
python:
  - "3.4"
services: sqlite3

install:
  - pip install -r requirements/common.pip
  - pip install -r requirements/dev-test.pip

before_script:
  - python manage.py migrate
  
script:
  - python manage.py test
