language: python
install:
  - pip install tox
  - pip install flake8
matrix:
  include:
    - python: "3.5"
      env: TOX_ENVS=py35-django22
    - python: "3.6"
      env: TOX_ENVS=py36-django22,py36-django30,py36-django31
    - python: "3.7"
      env: TOX_ENVS=py37-django22,py37-django30,py37-django31
    - python: "3.8"
      env: TOX_ENVS=py38-django30,py38-django31
before_script:
  - flake8 .
script:
  - tox -e $TOX_ENVS
deploy:
  provider: pypi
  user: james.mcmahon
  password: testpasswordfortravis
  on:
    tags: true
    repo: James1345/django-rest-knox
  only:
    - master
  distributions: "sdist bdist_wheel"
git:
  depth: false
